# Pipeline CommandAPI Tests

trigger:
<<<<<<< HEAD
- main
=======
- develop
>>>>>>> f30e47df4782571df0b35fab8bfe8f08ce5f1be4

pool:
  vmImage: 'ubuntu-latest'
  
variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'
